---
driver:
  name: vagrant

provisioner:
  name: chef_solo
  require_chef_omnibus: 10.32.2

platforms:
  - name: ubuntu-12.04

suites:
  - name: default
    run_list:
      - recipe[fake::default]
    attributes:
